// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEBuPbC1ymmYf0j8l_6KUSKiaQrHXkffc',
    appId: '1:749517081892:web:8fa2d644530874e18837b1',
    messagingSenderId: '749517081892',
    projectId: 'rcanews-6c5ae',
    authDomain: 'rcanews-6c5ae.firebaseapp.com',
    storageBucket: 'rcanews-6c5ae.appspot.com',
    measurementId: 'G-KSBJF6X440',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIAnzNCneBlUF7v-7HSYjsVVA9jdryutM',
    appId: '1:749517081892:android:12c6d2fe74895fce8837b1',
    messagingSenderId: '749517081892',
    projectId: 'rcanews-6c5ae',
    storageBucket: 'rcanews-6c5ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyyA74YQ9YCnz47oS3HRhqjGFdfjd2tFE',
    appId: '1:749517081892:ios:514812ce3decad028837b1',
    messagingSenderId: '749517081892',
    projectId: 'rcanews-6c5ae',
    storageBucket: 'rcanews-6c5ae.appspot.com',
    iosClientId: '749517081892-vujuh1ofjn2oquoqjach9p0h2ldr72lu.apps.googleusercontent.com',
    iosBundleId: 'com.smoothdesign.rcanews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyyA74YQ9YCnz47oS3HRhqjGFdfjd2tFE',
    appId: '1:749517081892:ios:514812ce3decad028837b1',
    messagingSenderId: '749517081892',
    projectId: 'rcanews-6c5ae',
    storageBucket: 'rcanews-6c5ae.appspot.com',
    iosClientId: '749517081892-vujuh1ofjn2oquoqjach9p0h2ldr72lu.apps.googleusercontent.com',
    iosBundleId: 'com.smoothdesign.rcanews',
  );
}
